import PageHero from '@/components/PageHero'
import ContactSidebar from '@/components/ContactSidebar'
import Link from 'next/link'

export const metadata = {
  title: `No Duty to Investigate Citizenship Absent Clear Evidence`,
  description: `Legal analysis from The Bianchi Law Group on New Jersey criminal defense law.`,
}

export default function Page() {
  return (
    <main>
      <PageHero title="No Duty to Investigate Citizenship Absent Clear Evidence" />
      <section style={{ backgroundColor: '#F0F5FA' }} className="py-14">
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">
            <article className="lg:col-span-2 bg-white rounded-lg p-8 shadow-sm">
              <p style={{ color: '#a61c23', fontSize: '12px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 16 }}>October 10, 2025</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: '1.4rem', fontWeight: 700, color: '#272727', margin: '1.5rem 0 0.5rem' }}>New Jersey Supreme Court Decision – Ineffective Assistance of Counsel / Immigration Consequences of Plea</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>On July 22, 2025, the New Jersey Supreme Court decided State v. Juan C. Hernandez-Peralta, ___ N.J. ___ (2025), which held that, under the circumstances, sentencing counsel was not constitutionally ineffective for failing to further investigate the defendant’s citizenship status beyond asking him if he was a United States citizen and receiving an unequivocal “yes,” and therefore not advising him that his plea could result in deportation.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: '1.4rem', fontWeight: 700, color: '#272727', margin: '1.5rem 0 0.5rem' }}>Facts and Procedural History Involving Ineffective Assistance of Counsel</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>In 2019, Juan C. Hernandez-Peralta pled guilty to three counts of third-degree burglary and one count of second-degree robbery. During the plea colloquy, he told the court he was a U.S. citizen and that he was born in New York, although he had been born in Mexico. He also represented on his plea form (the form was subsequently amended) that he was a U.S. citizen. However, the presentence report later stated defendant was born in Mexico but moved to New York as a toddler; several report fields — including citizenship status, Social Security number, and driver’s license number — were left blank. At sentencing, represented by a different public defender, Carol Wentworth, the presentence report was reviewed, and Wentworth directly asked him if he was a U.S. citizen. He again answered “yes.” The court asked no questions about defendant’s citizenship or place of birth, and the parties raised no information about either at the hearing. In accordance with the plea agreement, defendant was sentenced to five years of Recovery Court Probation.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: '1.4rem', fontWeight: 700, color: '#272727', margin: '1.5rem 0 0.5rem' }}>Post-Conviction Relief Claim Based on Ineffective Assistance of Counsel</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>Hernandez-Peralta twice violated probation. In subsequent hearings, he stated he was born in Mexico, but no citizenship issues were raised. After the second violation, his probation was terminated, and he was sentenced to five years in prison under the No Early Release Act. He did not appeal. In 2022, after receiving an immigration detainer, he filed for post-conviction relief (PCR), claiming ineffective assistance of counsel because he had not been properly advised of the immigration consequences of his plea. The PCR court found plea counsel effective but sentencing counsel ineffective for not investigating discrepancies in the presentence report. It held that defendant would have rejected the plea had he been advised of the immigration risks. The Appellate Division affirmed in part finding that Wentworth had failed to properly advise defendant of the immigration consequences but remanded to the PCR court to determine whether defendant could withdraw his plea.&nbsp;</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>Defendant was deported to Mexico after the New Jersey Supreme Court granted leave to appeal. The State agreed, however, that the case was not moot because defendant’s “ability to pursue immigration remedies that could allow him to return to the United States is contingent on whether he is entitled to relief in [this] action.”</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: '1.4rem', fontWeight: 700, color: '#272727', margin: '1.5rem 0 0.5rem' }}>New Jersey Supreme Court’s Ineffective Assistance of Counsel Analysis</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>The New Jersey Supreme Court reversed. Justice Wainer Apter, writing for the majority, emphasized that to prove ineffective assistance of counsel under Strickland v. Washington, 466 U.S. 668 (1984), a defendant must show both deficient performance and prejudice. Here, Wentworth’s reliance on Hernandez-Peralta’s repeated unequivocal assertions of citizenship — in his plea form, to plea counsel, and in court — was reasonable. The presentence report did not clearly contradict his statements, as being born outside the U.S. is consistent with citizenship through parentage or naturalization, and the missing fields could be explained by incomplete reporting, not necessarily non-citizenship. No clear indicia of non-citizenship, such as a green card or alien registration number, appeared in the materials she reviewed.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: '1.4rem', fontWeight: 700, color: '#272727', margin: '1.5rem 0 0.5rem' }}>Court’s Refusal to Expand Ineffective Assistance of Counsel Obligations</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>The Court declined to impose a constitutional duty on sentencing counsel to independently verify citizenship beyond asking the client. It also questioned whether the defendant was even deportable at the time of sentencing under federal law. Even assuming deficiency, the Court found no prejudice because the defendant had already pled guilty, and he failed to show a reasonable probability that competent performance at sentencing would have resulted in a successful motion to withdraw the plea under State v. Slater, 198 N.J. 145 (2009).&nbsp;</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: '1.4rem', fontWeight: 700, color: '#272727', margin: '1.5rem 0 0.5rem' }}>Dissenting Opinion on Ineffective Assistance of Counsel</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>Justice Noriega dissented, joined by Justice Fasciale, arguing that Padilla v. Kentucky, 559 U.S. 356 (2010), imposes an affirmative duty at the critical stage of sentencing to advise noncitizen clients of immigration consequences. Simply asking “Are you a U.S. citizen?” is inadequate. The dissent stressed that counsel should not rely solely on a client’s self-assessment, particularly when available records raise potential red flags, and contended that defendant Hernandez-Peralta’s convictions could have subjected him to removal proceedings at the time of his plea.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: '1.4rem', fontWeight: 700, color: '#272727', margin: '1.5rem 0 0.5rem' }}>Conclusion – Key Takeaways on Ineffective Assistance of Counsel</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>The Court’s holding establishes that, in New Jersey, absent clear evidence contradicting a defendant’s repeated assertions of citizenship, sentencing counsel is not constitutionally obligated to independently investigate citizenship status for immigration-consequence advisement. This decision narrows the scope of Padilla obligations at the sentencing stage, focusing on clear indicia rather than speculative red flags.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>Criminal law is complicated and constantly changing. If you are facing criminal charges, you should immediately contact our team of experienced former prosecutors to schedule a free case review with one of our expert criminal defense attorneys. A complete understanding of criminal law by your attorney is crucial to your defense. Your rights and freedoms are in jeopardy, and you owe it to yourself to act. We are available to provide immediate assistance and further counsel on your case at 862-225-1965.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>No aspect of this attorney advertisement has been approved by the Supreme Court of New Jersey</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>8 Campus Dr #105Parsippany, NJ 07054</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: '15px', lineHeight: 1.8, color: '#555', marginBottom: '1rem' }}>125 Half Mile Rd #200Red Bank, NJ 07701</p>
              <div className="mt-8 pt-6 border-t border-gray-100">
                <Link href="/blog" style={{ color: '#a61c23', fontWeight: 700 }} className="hover:underline">← Back to Blog</Link>
              </div>
            </article>
            <aside>
              <ContactSidebar />
            </aside>
          </div>
        </div>
      </section>
    </main>
  )
}
