export const PHONE = '(862) 292-4442';
export const PHONE_HREF = 'tel:8622924442';
export const ADDRESS = '65 Route 206, Suite 1, Stanhope, NJ 07874';
export const FIRM_NAME = 'The Bianchi Law Group, LLC';
export const LOGO = 'https://bianchilawgroup.com/wp-content/uploads/2025/06/Logo-1-1-580x61.png';

export const attorneys = [
  { slug: 'robert-bianchi-esq', name: 'Robert A. Bianchi, Esq.', title: 'Founding Partner', image: 'https://bianchilawgroup.com/wp-content/uploads/2025/07/bob_Bianchi.png', bio: 'Robert A. Bianchi is a highly acclaimed former Morris County Prosecutor and Founding Partner of The Bianchi Law Group, LLC. He has tried over 100 jury trials and is recognized nationally as a legal analyst on CNN, HLN, Fox News, and MSNBC. He is certified by the Supreme Court of New Jersey as a Criminal Trial Attorney.' },
  { slug: 'david-j-bruno-esq', name: 'David J. Bruno, Esq.', title: 'Partner', image: 'https://bianchilawgroup.com/wp-content/uploads/2025/07/David-J_team.png', bio: 'David J. Bruno is a Partner at The Bianchi Law Group, LLC. A former prosecutor, David has extensive experience in criminal defense and regularly appears on national television as a legal analyst.' },
  { slug: 'christina-hall-esq', name: 'Christina Hall, Esq.', title: 'Associate Attorney', image: 'https://bianchilawgroup.com/wp-content/uploads/2025/06/Christina-Hall-Esq.png', bio: 'Christina Hall, Esq. is an Associate Attorney at The Bianchi Law Group, LLC, bringing dedication and skilled legal advocacy to every case across a range of criminal defense matters in New Jersey.' },
  { slug: 'christopher-eaton-esq', name: 'Christopher A. Eaton, Esq.', title: 'Associate Attorney', image: 'https://bianchilawgroup.com/wp-content/uploads/2025/06/Image345.png', bio: 'Christopher A. Eaton, Esq. is a former Bergen County prosecutor who joined The Bianchi Law Group to represent those accused of serious criminal offenses. His background as a prosecutor gives invaluable insight into state tactics.' },
  { slug: 'danielle-esposito-esq', name: 'Danielle M. Esposito, Esq.', title: 'Associate Attorney', image: 'https://bianchilawgroup.com/wp-content/uploads/2025/07/Danielle_teamb.png', bio: 'Danielle M. Esposito, Esq. is an Associate Attorney at The Bianchi Law Group, LLC, providing compassionate and skilled representation to clients facing criminal charges throughout New Jersey.' },
  { slug: 'dennis-kessler-esq', name: 'Dennis Kessler, Esq.', title: 'Associate Attorney', image: 'https://bianchilawgroup.com/wp-content/uploads/2025/07/Dennis_teamm.png', bio: 'Dennis Kessler, Esq. is an Associate Attorney at The Bianchi Law Group, LLC with extensive experience in criminal law, committed to providing each client with the highest level of legal representation.' },
  { slug: 'paul-a-di-lella-esq', name: 'Paul A. Di Lella, Esq.', title: 'Associate Attorney', image: 'https://bianchilawgroup.com/wp-content/uploads/2025/06/Image345.png', bio: 'Paul A. Di Lella, Esq. is an Associate Attorney at The Bianchi Law Group, LLC, providing skilled legal representation to individuals facing criminal charges throughout New Jersey courts.' },
  { slug: 'tricia-h-margolis-esq', name: 'Tricia H. Margolis, Esq.', title: 'Associate Attorney', image: 'https://bianchilawgroup.com/wp-content/uploads/2025/06/Tricia.png', bio: 'Tricia H. Margolis, Esq. is an Associate Attorney at The Bianchi Law Group, LLC, dedicated to defending the rights of individuals accused of crimes in New Jersey.' },
];
