import PageHero from '@/components/PageHero'
import ContactSidebar from '@/components/ContactSidebar'
import Link from 'next/link'

export const metadata = {
  title: "New Jersey Criminal Appeals Attorneys",
  description: "The Bianchi Law Group - New Jersey Criminal Appeals Attorneys in New Jersey. Former prosecutors fighting for your rights. Free consultation: 862-292-4442.",
}

export default function Page() {
  return (
    <main>
      <PageHero title="New Jersey Criminal Appeals Attorneys" subtitle="Challenging Unjust Convictions in NJ Courts" />
      <section className="py-14" style={{ backgroundColor: '#F0F5FA' }}>
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">
            <div className="lg:col-span-2 bg-white rounded-lg p-8 shadow-sm">
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>At The Bianchi Law Group, our criminal defense attorneys do more than provide dedicated legal defense at the trial court level. We also offer appellate advocacy and fight to ensure that wrongful convictions, procedural errors, and constitutional violations do not stand. If you opt to appeal your conviction, it's important to work with a private practice attorney. Public defenders often have minimal experience in appellate court, and their caseloads are typically three times larger than average. Even worse, they often cannot take appeals to the federal courts.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Put simply, you need New Jersey appeals lawyers who can take your case the distance. That's what you'll find at The Bianchi Law Group. Contact us today for your free consultation.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>"I've Been Convicted: Can I do anything now?"</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>You can. A conviction is not necessarily the final word in your case. Generally, you have a right to an appeal and a right to seek other post-judgment relief. There are several options, including direct appeals and applications for post-conviction relief (PCR). A direct appeal challenges defects in the trial, such as the improper admission of certain evidence against you, incorrect jury charges, or an excessive sentence. An application for post-conviction relief is a collateral attack on the conviction, after exhausting the appeals process, typically based on constitutional violations or the ineffective assistance of trial counsel.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>These options are not just for people who have gone through the trial process. If you pled guilty instead of going to trial, you are still allowed to appeal your conviction or challenge your conviction through the post-conviction relief process. But you must act quickly: appeals must be filed within forty-five days from the date the Judgment of Conviction is entered (usually your sentencing date). You may not be sure whether a direct appeal or a post-conviction relief application is appropriate. To be safe, engage with appellate counsel as soon as possible so that none of your options are foreclosed to you.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>What Is Post-Conviction Relief?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Most people think of direct appeals when discussing the appellate process. We recently saw something play out on the national stage during the Alec Baldwin trial that could've resulted in such an appeal. When it was discovered that the prosecution withheld potentially important evidence, the judge decided that such prosecutorial misconduct had tainted the trial court. In this instance, the judge threw out the case immediately — but had the misconduct not been discovered until after the trial, a direct appeal would have been appropriate. Post-conviction relief is somewhat different.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Imagine a situation in the prior example where the evidence in question was never brought to the prosecutor. Baldwin could have been convicted and sentenced to prison. If someone had come in a month later with the new evidence in question, the celebrity may have been able to file for post-conviction relief. This is possible even after direct appeals have already failed. If the admission of this evidence could have affected the earlier conclusion of the original trial court, then the conviction may be turned over during the appeals process.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>"I want to appeal my conviction. What happens next?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Any appeals attempt involves a lot of writing and research. No matter what court you are appealing from, the next step involves the attorneys on both sides reading the transcripts of the pretrial proceedings and the trial and identifying the significant issues. They will research those issues, relying on case law from other, similar cases. The result of this intensive review is an appellate brief that crystallizes the main points the attorney is arguing on appeal.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>The pathway your case takes through the court system depends on where you were convicted. If you were convicted of a municipal offense, such as a DUI/DWI or a disorderly persons offense, your appeal takes place at the Superior Court in that county. There, a Superior Court judge will probably hold oral arguments for the attorneys. There are no witnesses since the Superior Court judge is limited primarily to the municipal judge's factual findings. After oral argument and reading the briefs, the Superior Court judge will issue a decision. After a decision, either side may appeal to the Superior Court, Appellate Division (or just "Appellate Division").</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>If you were convicted in the Superior Court, your appeal goes to the Appellate Division. Whether you were convicted in municipal court or Superior Court does not matter by the time you are in the Appellate Division. Once your case is in the Appellate Division, a panel of two or three judges will review the briefs. There may be an oral argument, depending on whether any of the attorneys request it or if the panel wishes to hold an oral argument. Again, there are no witnesses. After reviewing the briefs and any oral argument, the Appellate Division issues its decision.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>Can Your Case Make it to the New Jersey Supreme Court?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>In most cases, a negative decision by the Appellate Division ends the case. However, you can also petition the New Jersey Supreme Court for certification; in other words, ask the Supreme Court to hear the case. If the Supreme Court grants certification all seven justices will review the briefs and hold mandatory oral arguments. Often, when a case goes to the New Jersey Supreme Court, the eventual holding in the case will apply to everyone in the state.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Consequently, the briefs and oral arguments often cover public policy considerations in addition to the facts and issues in your case. Needless to say, a great deal of research, writing, and preparation goes into a New Jersey Supreme Court case. Our state Supreme Court only accepts cases they believe involve important legal matters. However, their acceptance is not an indication that your case will have a favorable outcome. At this point, the state appellate level may fail you, but there are still options available to you.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>In fact, New Jersey appeals lawyers could take your case all the way to the United States Supreme Court. There are a few steps between the state and federal courts, but once you're at the top level of judicial governance, questions of constitutional law are likely involved. The Supreme Court of the United States is the final step in the appeals process, and most cases, it will never make it to their docket. However, if you truly believe you've been wronged and the law supports you — our law firm will not stop fighting until you secure justice.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>What Are the Possible Outcomes of the Appeals Process?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Appellate work is important to our justice system. It ensures that abuses of the system do not go unanswered. However, many people are confused about what the process actually looks like. Ineffective counsel, improper jury instructions, and other appeals aren't just a win-lose situation. There are actually a variety of different possible outcomes, and while some are more beneficial than others, each of these results will help New Jersey appellate attorneys better guide you on your next move. The following are the potential outcomes you can expect:</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Clearly, these are complex potentialities. For instance, an overturned conviction may sound great on paper — even resulting in a person's release from incarceration and clearance of their criminal record. However, unless the Appellate Division found the defendant not guilty or the charges were dismissed, it's possible that the government may opt to retry the case. Similarly, a reduced sentence is always a blessing — but there's no guarantee that such a reduction will be significant. This is why you should always work with New Jersey appeals lawyers when trying to navigate the system. Taking on this task alone is a recipe for failure.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>At The Bianchi Law Group, we'll review your case and help you understand all your options. Contact us today to schedule your free consultation.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>Former Prosecutors With Experience at Every Level of the New Jersey Judiciary</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>The former prosecutors at The Bianchi Law Group, LLC have collective experience at every level of the New Jersey Judiciary, from municipal court to the New Jersey Supreme Court. This broad range of experience means our appeals are grounded in practical concerns and tailored to your matter. In other words, we fight for your interests when we pursue appellate or other post-judgment litigation. Our goal is always to secure the most favorable outcome possible for each of our clients, and sometimes, this happens after the conclusion of the original trial.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>The attorneys at The Bianchi Law Group, LLC have crossover experience. Our trial lawyers have argued or clerked for the appellate courts, and our appellate team has pretrial and trial litigation experience. Everyone understands the preparation that goes into a successful trial and a thorough appeal. Our team-based approach to every case melds the best that both types of New Jersey criminal defense attorneys have to offer: the real-world perspective of trial lawyers melded with the research and writing skills developed by appellate attorneys.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Whether you believe you had ineffective trial counsel, sat before an unrepresentative jury, or experienced any other improper situations at the trial level, you have the right to question your conviction. However, keep in mind that there are deadlines in the appeals process. If you miss one of these deadlines, you may have no additional options — even if it's highly likely that appellate judges would have sided with you. This is why you should visit an appellate law firm in New Jersey immediately. At The Bianchi Law Group, we can get started right away and preserve your right to appeal.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>"How can an appellate attorney help me before I have gone to trial?"</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Appellate attorneys' help is not limited to the appellate process. They are experts at spotting potential issues since they have seen it all in their research. As a result, pretrial litigation is thorough. Every issue that can be raised on your behalf will be, and our appellate team will help quarterback the pretrial strategy. Another benefit to having an appellate attorney involved in your case at an early stage is the ability to quickly appeal interlocutory (mid-litigation) decisions. Time is of the essence in these situations — particularly for those confined in state or federal custody.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>If the judge in your case issues an unfavorable decision, an appellate lawyer can help you make the call about whether to appeal the decision or move for reconsideration before the trial judge, as well as what arguments you want to raise. Having an appellate lawyer involved from the beginning gives our client an edge in these fast-paced proceedings and helps preserve all of the issues in your case. You also won't have to expend a large amount of resources paying a new attorney to get caught up on your case. Put simply, they'll already understand all the relevant facts.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Perhaps most importantly, involving a criminal defense team that includes attorneys with appellate experience means that the pretrial submissions will be thoroughly researched and persuasively written. Appellate attorneys are research and writing specialists and relentlessly prepare for oral arguments. Having an appellate lawyer involved early in your matter puts these skills to use in the trial court. Appellate attorneys multiply the firepower your criminal defense team brings to the courtroom arena.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>What does this mean? It means the potential for an unfair outcome is greatly reduced from the start. A New Jersey appeals attorney can spot issues before the trial concludes, and this may result in a favorable verdict, mistrial, or even having the case thrown out altogether. There are a lot of different outcomes, so it's important to understand your best options for moving forward. Our law firm is here to guide you through these difficult times. Contact us today.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>Contact Our New Jersey Appellate Lawyers Today</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>If you are interested in appealing or challenging your conviction, time is of the essence because you are limited to forty-five days to file notice of your appeal. Different state and federal courts are available, and any judge or panel that hears appeals may decide that you were unfairly treated at the trial level. Your conviction could be overturned, and you may be granted a new trial. In some situations, the state won't even bother to refile once they realize their mistakes have tainted the case. Regardless of your underlying situation, seeking help with these legal matters is critical.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>At The Bianchi Law Group, we'll gladly take on the lead counsel role in your appeals process. If it's proven that a lower court made a mistake or other official errors or misconduct occurred, your life may be able to go back to normal. Our law firm deals with appellate matters because we truly believe the application of justice should be unbiased, constitutional, and based on the law of the land. To ensure access to all of your post-judgment options, get started by speaking with a New Jersey appellate lawyer today.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Do not delay. Call The Bianchi Law Group, LLC at (862) 292-4442 to schedule your free consultation today and learn more about your post-judgment options.</p>
              <div className="mt-8 pt-6 border-t border-gray-100">
                <a href="tel:8622924442" className="btn-primary">
                  Call 862-292-4442 for a Free Consultation
                </a>
              </div>
            </div>
            <aside>
              <ContactSidebar />
              <div className="mt-6 bg-white rounded-lg shadow-sm p-6">
                <h3 style={{ fontFamily: "'Playfair Display',serif", fontWeight: 700, fontSize: "1.1rem", color: "#272727", marginBottom: 12 }}>Practice Areas</h3>
                <ul className="space-y-2 text-sm">
                  {[
                    ['DWI / DUI Defense', '/criminal-defense/dwi'],
                    ['Drug Crimes', '/criminal-defense/drug-crimes'],
                    ['Murder and Homicide', '/criminal-defense/murder'],
                    ['Robbery', '/criminal-defense/robbery'],
                    ['Domestic Violence', '/criminal-defense/domestic-violence'],
                    ['Appeals', '/criminal-defense/appeals'],
                    ['Municipal Court', '/municipal-court'],
                    ['Criminal Investigations', '/criminal-defense/criminal-investigations'],
                  ].map(([label, href]) => (
                    <li key={href}>
                      <Link href={href} style={{ color: '#a61c23' }} className="hover:underline">
                        &rsaquo; {label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </aside>
          </div>
        </div>
      </section>
    </main>
  )
}
