import PageHero from '@/components/PageHero'
import ContactSidebar from '@/components/ContactSidebar'
import Link from 'next/link'

export const metadata = {
  title: "New Jersey Domestic Violence Attorneys",
  description: "The Bianchi Law Group - New Jersey Domestic Violence Attorneys in New Jersey. Former prosecutors fighting for your rights. Free consultation: 862-292-4442.",
}

export default function Page() {
  return (
    <main>
      <PageHero title="New Jersey Domestic Violence Attorneys" subtitle="Striving to Secure Fair Outcomes for Our Clients" />
      <section className="py-14" style={{ backgroundColor: '#F0F5FA' }}>
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">
            <div className="lg:col-span-2 bg-white rounded-lg p-8 shadow-sm">
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>At The Bianchi Law Group, we understand that you need more than just a legal advocate. You also need a team that will be compassionate throughout this ordeal. Our team of former prosecutors knows how to handle these stressful situations and recognizes that a domestic violence case can impact your life far beyond the courtroom. At The Bianchi Law Group, LLC, we offer a free consultation to anyone facing domestic violence or a related charge in family court or criminal court — because no one should have to pay just to understand their rights.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>New Jersey domestic violence law is complex, but we can guide you through the difficulties ahead.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>How Are Domestic Violence Charges Handled Under the Domestic Violence Act?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Any experienced criminal defense attorney can tell you that no two domestic violence cases are the same. The legal framework that primarily lays out how such cases are prosecuted exists thanks to the Prevention of Domestic Violence Act (PDVA), N.J.S.A. 2C:25-17 to -35. This law designates the various criminal offenses that qualify as domestic violence when committed against a qualifying victim. It's important to remember that no actual act of violence has to occur to an alleged victim for charges to be brought. While violent crimes certainly qualify, there are a variety of charges that fall under this umbrella.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Clearly, this is a broad range of crimes. What may be a simple petty or fourth-degree offense can suddenly become much more serious when the alleged victim of such crimes falls into specific categories. These categories include a spouse or former spouse, current or former household member, individuals in a dating relationship, and individuals who have a child in common. Depending on the underlying charge and severity of the alleged crime, potential penalties can differ significantly. However, those charged with a crime of the first degree could end up imprisoned for 20 years.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>In many domestic violence cases, police and prosecutors will believe the apparent victim. This has become more common in today's social environment — now that it's become obvious that countless victims have been silenced over the years. However, the government's attempt to be "safe instead of sorry" can result in innocent individuals facing unfair outcomes. If you've been charged with a crime against qualifying individuals, you need the legal services of an experienced New Jersey domestic violence attorney. That's precisely what we offer at The Bianchi Law Group.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>What Can I Do if I am Being Abused?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Domestic violence is a pattern of emotional, physical, verbal, and sexual abuse that covers a range of cyclical behaviors. These abusive acts are codified in the New Jersey Criminal Code and include indictable offenses, such as aggravated assault and sexual assault, as well as disorderly persons offenses, such as harassment, simple assault, and criminal mischief. If you are surviving in such a cycle, you need to know that it often becomes more frequent and more severe over time.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>You also need to know that you can break free of the cycle and have champions at The Bianchi Law Group, LLC. As former prosecutors, our attorneys have prosecuted domestic violence cases and understand what you have gone through. They are ready to help you protect yourself and offer you compassionate strength to see you through this ordeal. Our experienced domestic violence attorneys in New Jersey can review your situation and provide guidance on how to move forward.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Unfortunately, it's not always enough that an abuser has taken someone's mental happiness away. Statistics show that certain victims of intimate partner violence (IPV) are falsely accused of domestic violence at an alarming rate. This means you could face criminal proceedings when you're the victim. In such situations, it's critical that you seek legal representation. Without a dedicated attorney on your side, the potential consequences could be life-altering.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>What Penalties Exist for Domestic Violence Cases in New Jersey?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>The charges one faces after being convicted of domestic violence vary depending on the severity of the underlying act. Some domestic violence cases involve actions that constitute a disorderly persons offense, such as harassment or a simple assault. For a petty disorderly persons offense, the court may sentence the defendant to jail time or impose hefty fines. Other cases involve more serious acts that the New Jersey Criminal Code identifies as indictable offenses, such as aggravated assault. For such offenses, the court can impose prison time, extensive fines, and other sentencing consequences.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Many domestic violence cases also result in a temporary restraining order issued by the family court. A restraining order is an order from a judge directing one person not to do something, such as make contact with another individual, enter their home, or visit their workplace. There are collateral consequences to being subject to a restraining order, such as losing parenting time or administrative difficulties for any professional licenses you may hold. If you have been falsely accused of domestic abuse and face a restraining order, you need holistic legal advice from a law attorney who understands the magnitude of the consequences you are facing.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Put simply, our criminal defense attorneys understand that those who face domestic violence charges are up against difficulties that other defendants do not experience. Mere accusations can interfere with child custody rights. With the wide availability of "mugshot tabloids" and public records websites, individuals arrested for violence or subject to a domestic violence order may also have their reputations ruined. If convicted, the person accused of the crime could lose the right to vote, bear arms, and other fundamental freedoms. Fortunately, you don't have to go through this alone. Contact our New Jersey domestic violence lawyers today for assistance.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>Why Hire a Domestic Violence Lawyer NJ if You've Been Accused of Domestic Violence?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>There are a number of similarities between a Civil Complaint alleging domestic violence and a criminal complaint alleging domestic violence. The most important similarity between the two is if there is a judgment against you, you face serious consequences that impact all areas of your life. Legal consequences aside, you will also endure unquantifiable harm in your family relationships, such as those with your children. Your constitutional rights may be impacted, just as they would be in a traditional criminal case. One thing is clear: there is a great deal of overlap between criminal proceedings and civil domestic violence proceedings.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>And even if there is no criminal case against you now, one could quickly develop if a Final Restraining Order (FRO) is issued against you and you violate that FRO in any way. You also risk facing criminal domestic violence charges brought by your county prosecutor's office based on the acts underlying the domestic violence accusations against you. Because of the overlap between a civil domestic violence proceeding before the family court and the potential for criminal proceedings, it is best to hire a lawyer who is familiar with both worlds. Also, like in criminal cases, both sides conduct an investigation. But unlike criminal cases, FRO hearings are held within weeks of the issuance of the temporary restraining order (TRO).</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>That means that the investigation takes place on a short timeline. That also means that your attorney should be someone well-versed in investigative tactics and how to use that evidence in your case. A specialized criminal defense lawyer will leverage the evidence gathered during the investigation. Our team of exclusively former prosecutors have investigated a wide range of matters, including domestic violence charges. As a result, they are knowledgeable about the investigative process and use that insight to take charge of the investigation. We strive to produce the best case possible, and the best case begins with the best investigation.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>When you work with one of the former prosecutors at The Bianchi Law Group, LLC, you can trust that our attorneys will stop at nothing to advocate on your behalf. Your domestic violence defense attorney will compassionately listen to you and present your case to the judge. Finally, the FRO hearing is a lot like a criminal trial. There are opening and closing statements by the lawyers. There may be witnesses. There could be objections based on evidentiary issues – and no one knows The Rules of Evidence like a former prosecutor. Our trial experience as former prosecutors naturally translates to the FRO hearing setting. Because of that experience, we stand ready to zealously advocate for you at the FRO hearing.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>How Do Domestic Violence Charges Affect Family Law Matters?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>If you're going through a divorce or child custody dispute, you clearly have a lot on your plate. Unfortunately, you'll need more than a family law attorney if you're accused of domestic violence. That's because allegations of violence can have a direct effect on the outcome of domestic legal issues. These claims can be used as grounds for divorce by claiming extreme cruelty, and while there's no legal mandate that violence in a relationship must affect asset division and spousal support payments, the circumstances of your situation could be factored into the judge's final decision.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Similarly, allegations only affect child support issues if certain criteria are met. For instance, parental targets of restraining orders may be ordered to provide temporary financial support if they're removed from the child's home life. However, there are significant potential effects when it comes to child custody. Under New Jersey law there is a rebut table presumption that a parent convicted of domestic violence should not be awarded custody. This presumption can be extremely difficult to overcome, as all decisions involving children are based on the best interests of the child.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>At The Bianchi Law Group, our New Jersey domestic violence lawyers have also spoken with parents scared of losing their visitation rights. Many parents who come into our law offices are unsure how they should respond to allegations. It's smart to be concerned, because the courts may order supervised visitation if they believe the parent is a danger to the child. In some situations, the courts have even terminated parental rights. Put simply, the effects of domestic violence allegations on family law issues cannot be overstated. You need a dedicated attorney on your side.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>What Happens if You Violate Restraining Orders?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Whether you're facing a temporary restraining order (TRO) or a final restraining order (FRO), it's important that you abide by its conditions. That's because the violation of such an order is considered its own criminal offense in New Jersey. N.J.S.A. 2C:29-19 (Contempt). Any experienced lawyer can tell you that you don't have to do anything drastic to be charged with violating a restraining order. Yes, causing bodily injury will result in significant consequences — but even contacting someone when ordered not to can lead to major penalties. Police are required to make an arrest if they believe an order has been violated.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Such violations can include:</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>As a fourth-degree crime, violation of restraining orders can result in an 18-month prison sentence. Fines can also reach up to $10,000 — and those accused of repeat violations will face sentence enhancements. Even if you and the alleged victim have made amends and want to spend time together, you need to avoid doing so and stay within the confines of your court order. "We're getting along now" is not a legal defense for restraining order violations, and you could find yourself incarcerated even if your actions were invited by the protected person.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Put simply, you need to go the legal route of overturning an order if this is what the alleged victim wants. Contact our law offices today to learn how a New Jersey domestic violence attorney can assist.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>What's the Best Defense Against Domestic Violence Charges in the Legal System?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Choosing the best defense strategy for your case can be a difficult endeavor, and it should only be done with the assistance of a domestic violence attorney in New Jersey. That's because potential defenses can vary drastically based on the circumstances of a case and the underlying charge. That's because the elements of crimes differ — even when they all qualify as domestic violence. Since the elements of criminal restraint are not the same as those for terroristic threats and other charges, you need to sit down with a lawyer to figure out the best approach.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>However, there are certain defense strategies that apply to most — if not all — domestic violence charges. In fact, some of these legal defenses can be used for everything from a traffic offense to first-degree murder:</p>
              <div className="mt-8 pt-6 border-t border-gray-100">
                <a href="tel:8622924442" className="btn-primary">
                  Call 862-292-4442 for a Free Consultation
                </a>
              </div>
            </div>
            <aside>
              <ContactSidebar />
              <div className="mt-6 bg-white rounded-lg shadow-sm p-6">
                <h3 style={{ fontFamily: "'Playfair Display',serif", fontWeight: 700, fontSize: "1.1rem", color: "#272727", marginBottom: 12 }}>Practice Areas</h3>
                <ul className="space-y-2 text-sm">
                  {[
                    ['DWI / DUI Defense', '/criminal-defense/dwi'],
                    ['Drug Crimes', '/criminal-defense/drug-crimes'],
                    ['Murder and Homicide', '/criminal-defense/murder'],
                    ['Robbery', '/criminal-defense/robbery'],
                    ['Domestic Violence', '/criminal-defense/domestic-violence'],
                    ['Appeals', '/criminal-defense/appeals'],
                    ['Municipal Court', '/municipal-court'],
                    ['Criminal Investigations', '/criminal-defense/criminal-investigations'],
                  ].map(([label, href]) => (
                    <li key={href}>
                      <Link href={href} style={{ color: '#a61c23' }} className="hover:underline">
                        &rsaquo; {label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </aside>
          </div>
        </div>
      </section>
    </main>
  )
}
