import PageHero from '@/components/PageHero'
import ContactSidebar from '@/components/ContactSidebar'
import Link from 'next/link'

export const metadata = {
  title: "New Jersey Robbery Attorneys",
  description: "The Bianchi Law Group - New Jersey Robbery Attorneys in New Jersey. Former prosecutors fighting for your rights. Free consultation: 862-292-4442.",
}

export default function Page() {
  return (
    <main>
      <PageHero title="New Jersey Robbery Attorneys" subtitle="Committed to Helping Clients Avoid Felony Convictions" />
      <section className="py-14" style={{ backgroundColor: '#F0F5FA' }}>
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">
            <div className="lg:col-span-2 bg-white rounded-lg p-8 shadow-sm">
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>At The Bianchi Law Group, we understand that you're up against a terrifying reality. A robbery conviction will almost always lead to significant jail time — especially if the prosecution claims the defendant inflicted injury during the alleged offense. It's almost impossible to exaggerate the effects that such a conviction will have on a person's life. Even after a person is no longer incarcerated, a felony on their record can affect their rights, freedoms, and ability to lead a normal life forever. Fortunately, this isn't a battle you have to fight alone. A criminal defense attorney at our law firm can assist.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Contact us today for your free initial consultation.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>Robbery Penalties in New Jersey</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Robbery is a crime of the second degree, except that it is a crime of the first degree if, in the course of committing the theft, the actor attempts to kill anyone, purposely inflicts or attempts to inflict serious bodily injury, or is armed with, or uses or threatens the immediate use of a deadly weapon. N.J.S.A, 2C:15-1. Crimes in the first degree can be punishable from 10 years to 20 years in New Jersey State Prison. Crimes in the second degree can be punishable from 5 years to 10 years in New Jersey State Prison.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>The Sentencing Judge may also order fines and restitution as prescribed by N.J.S.A. 2C:43-3 for all robbery convictions in New Jersey. As former prosecutors, our New Jersey robbery defense attorneys have seen how strict sentencing can be when someone is convicted of a violent crime. In addition to the legal repercussions, an individual may also have difficulty engaging in normal activities in the future (e.g., voting, owning a firearm, securing housing). Put simply, the penalties are severe.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>However, they're not always unavoidable. Whether you're charged with a second or first-degree crime, we'll fight to secure a favorable outcome on your behalf. Contact us today to learn more.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>What Constitutes "Serious Bodily Injury"?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Since the threat or infliction of serious bodily injury could mean the difference between first or second-degree robbery charges, it's important to understand what this term means under New Jersey law. A person inflicts bodily injury of a severe magnitude if their actions create a substantial risk of death or serious, permanent disfigurement or a protracted impairment or loss of the function of any organ or bodily member. N.J.S.A. 2C:11-1. This can be anything from a fractured skull to internal organ damage.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>The important thing to remember is that actually inflicting such injury is not necessary for the state to bring first-degree robbery charges. The mere threat of inflicting such injury is enough. A person who has no plans to hurt anyone can still be charged with a first-degree crime that's punishable by up to 20 years in prison if the alleged victim claims they were threatened with harm. This is one of the few times a person's words can result in severe criminal charges, so make sure you're taking your situation seriously.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Contact our law firm today for a free initial consultation.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>Certified Criminal Trial Attorneys by the New Jersey Supreme Court</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Partners Robert A. Bianchi and David J. Bruno are also both certified by the Supreme Court of New Jersey as Criminal Trial Attorneys. In New Jersey, the New Jersey Supreme Court has a certification committee that classifies certain New Jersey Lawyers as Certified Trial Attorneys. The process requires the prospective attorneys to satisfy strict criteria, including extensive jury trials, a primary focus on criminal law, an application submission, a peer review process, a character and background check, and passing a written examination.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Only 250 of over 98,000 lawyers (less than 1%) are designated as certified criminal trial attorneys by the New Jersey Supreme Court. This should be an important factor in finding a New Jersey criminal defense attorney to represent you. Many New Jersey Lawyers describe themselves as trial attorneys, but most do not have the New Jersey Court's distinction as Certified Criminal Trial Attorney. When charged with first or second-degree robbery, this distinction couldn't be more important — because certified trial lawyers have proven themselves during litigation.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>As former prosecutors, our legal experience in the courtroom goes back much further than our criminal defense career. We know that a fair outcome won't always be possible pre-trial, so if the prosecution wants a guilty verdict, then we will make them fight for it. All we have to do is establish reasonable doubt that a client committed the alleged offense, and from that point, the prosecutors simply don't have a case. Knowing that you have a Certified Criminal Trial Attorney on your side, the government may even be more open to a fair plea deal or dropping charges altogether.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>2C:15-1- New Jersey’s Robbery Statute</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>New Jersey criminal code defines robbery in a very specific manner. To secure a conviction, the prosecutor must review the elements of the law and prove that each applies to the defendant's case. This is true for the prosecution of all criminal acts. If they're unable to prove these elements beyond a reasonable doubt, then a defendant cannot be convicted. While innocent people certainly face criminal penalties on occasion, understanding the law can give you an advantage when defending yourself.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>State law defines robbery in the following manner:</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>(1) Inflicts bodily injury or uses force upon another; or (2) Threatens another with or purposely puts him in fear of immediate bodily injury; or (3) Commits or threatens immediately to commit any crime of the first or second degree.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>An act shall be deemed to be included in the phrase "in the course of committing a theft" if it occurs in an attempt to commit theft or in immediate flight after the attempt or commission.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>N.J.S.A. 2C:20-3 defines theft. A person is guilty of theft if he unlawfully takes or exercises unlawful control over the movable property of another with the purpose of depriving him thereof.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>N.J.S.A. 2C:15-1 provides that robbery is a crime of the second degree, except that it is a crime of the first degree if, in the course of committing the theft, the actor attempts to kill anyone, purposely inflicts or attempts to inflict serious bodily injury, or is armed with, or uses or threatens the immediate use of a deadly weapon.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>What Are the Penalties for Armed Robbery Charges in New Jersey?</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Not all robbery charges in New Jersey are the same, and one of the primary distinguishing factors is whether a weapon was used during the commission of the alleged offense. While first-degree robbery can involve attempted murder or infliction and threats of serious bodily injury, such charges are also common when a deadly weapon is used. Since it's categorized as a first-degree crime, the potential prison sentence is from 10-20 years.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Unfortunately, for those convicted, the possibility of early parole isn't very promising. Under the No Early Release Act, individuals convicted of first-degree robbery must serve at least 85% of their sentence before being eligible for parole. No matter how well-behaved a person is in prison or how rehabilitated they become, strict laws in our state's criminal justice system ensure that no leniency is provided. That's why you need an armed robbery lawyer in New Jersey fighting on your behalf.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Contact us today for your free consultation.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>Trial Ready New Jersey Criminal Lawyers</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Like in all of our cases handled at the Bianchi Law Group, our experienced team of former prosecutors are there to make sure the Government can prove its case beyond a reasonable doubt. If our attorneys cannot resolve the case with a dismissal or a fair and just plea bargain, our lawyers at The Bianchi Law Group will not hesitate to select a jury and take the case to trial. That is what we do and what distinguishes us from other attorneys.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>We are former prosecutors, trial-tested, and certified by the New Jersey Supreme Court as certified criminal trial attorneys. Whenever it's in our client's best interests, we'll fight all the way to a jury verdict. A robbery conviction will leave a lasting blemish on a person's record — forever interfering with their ability to secure employment, housing, education, and even legal immigration status. Sadly, this may be the least of a person's worries if they're sentenced to a 10- to 20-year prison sentence.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Any violent crime will have severe penalties under the law. While plea negotiations are certainly an option, our New Jersey robbery lawyers will never simply accept a deal to speed things along. Our primary goal is always to secure the best possible outcome on behalf of our clients. This can look very different based on the circumstances of the case, but that's what we'll always fight for. Contact us today for your free consultation.</p>
              <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.4rem", fontWeight: 700, color: "#272727", margin: "1.5rem 0 0.5rem" }}>Contact Our New Jersey Robbery Lawyers Today</h2>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>At a minimum, robbery charges in New Jersey will be charged as a second-degree crime. In terms of these charges, this is a best-case scenario. However, it probably doesn't seem "best-case" since a person could be sentenced to up to a decade in prison if convicted. The criminal justice system takes this crime extremely seriously, as it's viewed as more violent and harmful than traditional theft. That's why anyone charged with robbery offenses should understand the severity of their situation. Without proper legal counsel, these criminal charges could destroy your life.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>At The Bianchi Law Group, our dedicated team of legal professionals will handle your New Jersey robbery case as if it's the most important thing on our desks — because, in many ways, it absolutely is. We take our reputation very seriously, and when we offer legal representation to a client, we want them to know that we will fight diligently and aggressively to secure the best possible outcome in their case. Contact Former Morris County Prosecutor Robert A. Bianchi, Esq. and David J. Bruno, Esq. at The Bianchi Law Group, LLC today at (862) 292-4442 for a free consultation.</p>
              <p style={{ fontFamily: "'Nunito Sans',sans-serif", fontSize: "15px", lineHeight: 1.8, color: "#555", marginBottom: "1rem" }}>Our New Jersey robbery lawyers are here to help.</p>
              <div className="mt-8 pt-6 border-t border-gray-100">
                <a href="tel:8622924442" className="btn-primary">
                  Call 862-292-4442 for a Free Consultation
                </a>
              </div>
            </div>
            <aside>
              <ContactSidebar />
              <div className="mt-6 bg-white rounded-lg shadow-sm p-6">
                <h3 style={{ fontFamily: "'Playfair Display',serif", fontWeight: 700, fontSize: "1.1rem", color: "#272727", marginBottom: 12 }}>Practice Areas</h3>
                <ul className="space-y-2 text-sm">
                  {[
                    ['DWI / DUI Defense', '/criminal-defense/dwi'],
                    ['Drug Crimes', '/criminal-defense/drug-crimes'],
                    ['Murder and Homicide', '/criminal-defense/murder'],
                    ['Robbery', '/criminal-defense/robbery'],
                    ['Domestic Violence', '/criminal-defense/domestic-violence'],
                    ['Appeals', '/criminal-defense/appeals'],
                    ['Municipal Court', '/municipal-court'],
                    ['Criminal Investigations', '/criminal-defense/criminal-investigations'],
                  ].map(([label, href]) => (
                    <li key={href}>
                      <Link href={href} style={{ color: '#a61c23' }} className="hover:underline">
                        &rsaquo; {label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </aside>
          </div>
        </div>
      </section>
    </main>
  )
}
